services:
  qucore_landing_frontend:
    build: .
    env_file:
      - .env
      - .env.prod
    container_name: client
    ports:
      - '3000:3000'
    networks: [qucore_landing_network]

networks:
  qucore_landing_network:
    external: true
